(module
  (@interface func)
  (@interface func (param $foo string)
    arg.get $foo
  )
)

(; CHECK-ALL:
  (module
    (@interface type (func))
    (@interface type (func (param string)))
    (@interface func (type 0))
    (@interface func (type 1)
      arg.get 0))
;)
