(module
  (import "a" "b" (func $core))
  (import "b" "c" (func))
  (import "b" "c" (func $bar))

  (@interface implement (import "a" "b") (func 100))
  (@interface implement (func $bar) (func 100))
  (@interface implement (func 0) (func 100))

  (@interface implement (func $core))
  (@interface implement (func 0) (param s32))
)
