;; parse-fail

(module
  (@interface implement (import "" "") (func 1)))

(; CHECK-ALL:
  import of `` from `` not found in core module
       --> tests/implement1.wit:4:15
        |
      4 |   (@interface implement (import "" "") (func 1)))
        |               ^

  Backtrace disabled; run with RUST_LIB_BACKTRACE=1 environment variable to display a backtrace
;)
