;; parse-fail

x

(; CHECK-ALL:
  expected `(`
       --> tests/not-interface.wit:3:1
        |
      3 | x
        | ^

  Backtrace disabled; run with RUST_LIB_BACKTRACE=1 environment variable to display a backtrace
;)
