(module
  (@interface type (func))
  (@interface type (func (param f32)))
  (@interface type (func (result f64)))
  (@interface type (func (param f32) (param string) (result f64)))
  (@interface type (func (param f32) (param string) (result f64) (result u8)))
  (@interface type (func
    (param u8)
    (param u16)
    (param u32)
    (param u64)
    (param s8)
    (param s16)
    (param s32)
    (param s64)
    (param f32)
    (param f64)
    (param string)
    ))
  (@interface type (func (result f32)))
  (@interface type (func (result f64)))
  (@interface type (func (result u8)))
  (@interface type (func (result u16)))
  (@interface type (func (result u32)))
  (@interface type (func (result u64)))
  (@interface type (func (result string)))
  (@interface type (func (result s8)))
  (@interface type (func (result s16)))
  (@interface type (func (result s32)))
  (@interface type (func (result s64)))

  ;; repeated interfaces
  (@interface type (func (param s8) (result s8)))
  (@interface type (func (param s8) (result s8)))

  ;; named
  (@interface type $bar (func))
)

(; CHECK-ALL:
(module
  (@interface type (;0;) (func))
  (@interface type (;1;) (func (param f32)))
  (@interface type (;2;) (func (result f64)))
  (@interface type (;3;) (func (param f32) (param string) (result f64)))
  (@interface type (;4;) (func (param f32) (param string) (result f64) (result u8)))
  (@interface type (;5;) (func (param u8) (param u16) (param u32) (param u64) (param s8) (param s16) (param s32) (param s64) (param f32) (param f64) (param string)))
  (@interface type (;6;) (func (result f32)))
  (@interface type (;7;) (func (result f64)))
  (@interface type (;8;) (func (result u8)))
  (@interface type (;9;) (func (result u16)))
  (@interface type (;10;) (func (result u32)))
  (@interface type (;11;) (func (result u64)))
  (@interface type (;12;) (func (result string)))
  (@interface type (;13;) (func (result s8)))
  (@interface type (;14;) (func (result s16)))
  (@interface type (;15;) (func (result s32)))
  (@interface type (;16;) (func (result s64)))
  (@interface type (;17;) (func (param s8) (result s8)))
  (@interface type (;18;) (func (param s8) (result s8)))
  (@interface type (;19;) (func)))
;)
